Resources:
    RequestParamsValidator:
       Type: AWS::ApiGateway::RequestValidator
       Properties:
              RestApiId:
                    Ref: ApiGatewayRestApi
              ValidateRequestBody: false
              ValidateRequestParameters: true